openapi: 3.0.3
info:
  title: EDWebApi
  description: EDWebApi
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /users:
    get:
      tags: [User]
      description: Returns all users
      operationId: getAll
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        401:
          description: No permissions
    post:
      tags: [User]
      description: Create new user
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
        required: true
      responses:
        200:
          description: Success
        400:
          description: Bad

  /users/{uuid}:
    get:
      tags: [User]
      description: Returns user with given uuid
      operationId: get
      parameters:
        - name: 'uuid'
          in: path
          required: true
          description: uuid of user that will be returned
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid id format

    delete:
      tags: [User]
      description: Deletes user
      operationId: delete
      parameters:
        - name: 'uuid'
          in: path
          required: true
          description: id of user that will be returned
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Success
        400:
          description: Bad request
        404:
          description: User with given UUID not found


components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        uuid:
          type: string
          format: uuid
      required:
        - name
        - uuid

    CreateUser:
      type: object
      properties:
        name:
          type: string
        password:
          type: string
      required:
        - name
        - password


